### ISSUE TITLE
Issue 9: アカウント削除機能の実装

### ISSUE THREAD

**Issue by Hiroshift** [Hiroshift/setsuyaku_income#12]
#### **目的**
ユーザーが自身のアカウントを削除できる機能を実装し、データベースから関連データを完全に削除できるようにする。

---

#### **タスク**
1. **アカウント削除機能の確認**
   - Deviseにおけるアカウント削除機能（`destroy`アクション）の動作を確認。

2. **`User`モデルの更新**
   - `has_many :recordings, dependent: :destroy`を追加して、アカウント削除時に関連データも削除。

3. **コントローラーの拡張**
   - `Users::RegistrationsController`をカスタマイズして、削除時に適切なフラッシュメッセージを表示。

4. **UIの実装**
   - プロフィール編集画面に「アカウントを削除する」ボタンを追加。
   - ボタン押下時に確認モーダルを表示（JavaScriptを活用）。

5. **テストの実装**
   - RSpecで以下をテスト：
     - アカウント削除が正常に動作すること。
     - 削除時に`recordings`データも削除されること。
     - 削除後、ログアウト状態でトップページにリダイレクトされること。

---

##### **1. Userモデルの更新**
```ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recordings, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 50 }
  validates :hourly_rate, presence: true, numericality: { greater_than_or_equal_to: 0 }
  # パスワードのバリデーションを条件付きに設定
  validates :password, format: {
    with: /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]+\z/,
    message: 'is invalid. Include both letters and numbers'
  }, allow_nil: true
end
```

##### **2. Users::RegistrationsControllerのカスタマイズ**
```ruby
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    if current_user.destroy
      flash[:notice] = "アカウントが削除されました。"
      redirect_to after_sign_out_path_for(:user)
    else
      flash[:alert] = "アカウントの削除に失敗しました。もう一度お試しください。"
      redirect_to edit_user_registration_path
    end
  end

  protected

  # パスワードなしで情報を更新できるようにする
  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank?
      resource.update_without_password(params)
    else
      resource.update(params)
    end
  end

  # サインアップ後のリダイレクト先を指定
  def after_sign_up_path_for(_resource)
    root_path # ホーム画面に遷移
  end

  # アカウント削除後のリダイレクト先を指定
  def after_destroy_path_for(_resource)
    root_path # ホーム画面に遷移
  end
end
```

##### **3. ルーティングの設定**
```ruby
devise_for :users, controllers: { registrations: 'users/registrations' }
```

##### **4. プロフィール編集画面の更新**
```erb
<!-- キャンセルの誘導文とボタン -->
<div class="cancel-container">
  <p>編集をキャンセルする場合はこちら：</p>
  <%= link_to "ホームに戻る", root_path, class: "btn btn-secondary" %>
</div>

<!-- アカウント削除ボタン -->
<div class="delete-account-container">
  <p>アカウントを削除する場合はこちら：</p>
  <button id="delete-account-btn" class="btn btn-danger">アカウントを削除する</button>
</div>

<!-- アカウント削除確認モーダル -->
<div id="delete-confirm-modal" class="modal">
  <div class="modal-content">
    <p>本当にアカウントを削除しますか？</p>
    <%= button_to "削除する", registration_path(resource), method: :delete, class: "btn btn-danger" %>
    <button class="btn btn-secondary">キャンセル</button>
  </div>
</div>
```
##### **5. javascriptファイルの作成**

```java
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"

document.addEventListener("turbo:load", () => {
  const deleteAccountBtn = document.getElementById("delete-account-btn");
  const deleteConfirmModal = document.getElementById("delete-confirm-modal");
  const cancelBtn = document.querySelector("#delete-confirm-modal .btn-secondary");

  if (deleteAccountBtn && deleteConfirmModal) {
    deleteAccountBtn.addEventListener("click", () => {
      deleteConfirmModal.style.display = "block";
    });

    if (cancelBtn) {
      cancelBtn.addEventListener("click", () => {
        deleteConfirmModal.style.display = "none";
      });
    }

    window.addEventListener("click", (event) => {
      if (event.target === deleteConfirmModal) {
        deleteConfirmModal.style.display = "none";
      }
    });
  }
});
```

##### **6. CSSの追加（Javascript用）**
```CSS
/* アカウント削除ボタンのスタイル */
.delete-account-container {
  margin-top: 20px; /* 上に余白を追加 */
  text-align: center; /* テキストを中央寄せ */
}

.delete-account-container .btn-danger {
  display: inline-block; /* インラインブロック表示 */
  padding: 12px 24px; /* ボタン内の余白を設定 */
  border-radius: 5px; /* ボタンの角を丸くする */
  font-size: 1rem; /* フォントサイズを設定 */
  font-weight: bold; /* 太字に設定 */
  text-decoration: none; /* 下線を除去 */
  background-color: #e62c3c; /* 削除ボタンの赤色 */
  color: #ffffff; /* ボタン文字を白色に設定 */
  border: none; /* 枠線を除去 */
  cursor: pointer; /* ポインターを表示 */
  transition: background-color 0.3s ease; /* 背景色の遷移をスムーズに */
}

.delete-account-container .btn-danger:hover {
  background-color: #c82333; /* ホバー時の濃い赤色 */
}

/* モーダル全体のスタイル */
.modal {
  display: none; /* デフォルトは非表示 */
  position: fixed; /* 固定位置 */
  z-index: 1000; /* モーダルを最前面に */
  left: 0; /* 左端から */
  top: 0; /* 上端から */
  width: 100%; /* 画面幅全体 */
  height: 100%; /* 画面高さ全体 */
  overflow: auto; /* スクロール可能 */
  background-color: rgba(0, 0, 0, 0.7); /* 背景を暗く半透明に */
}

/* モーダルの内容部分 */
.modal-content {
  background-color: #ffffff; /* 背景色を白に設定 */
  margin: 15% auto; /* 上下中央に配置 */
  padding: 20px; /* 内側の余白 */
  border: 1px solid #ddd; /* 薄い枠線を追加 */
  width: 90%; /* 幅を画面の90%に設定 */
  max-width: 500px; /* 最大幅を500pxに制限 */
  text-align: center; /* テキストを中央寄せ */
  border-radius: 10px; /* 角を丸くする */
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* 影を追加 */
  animation: fadeIn 0.3s ease-in-out; /* フェードインのアニメーション */
}

/* モーダル内のタイトル */
.modal-content p {
  font-size: 1.2rem; /* フォントサイズを少し大きめに */
  color: #212529; /* 文字色を濃いグレーに設定 */
  margin-bottom: 20px; /* 下に余白を追加 */
}

/* モーダル内のボタンのスタイルを統一 */
.modal-content .btn {
  display: inline-block; /* インラインブロックで表示 */
  padding: 10px 20px; /* 内側の余白を追加 */
  border-radius: 5px; /* ボタンの角を丸くする */
  font-size: 1rem; /* フォントサイズを統一 */
  text-decoration: none; /* 下線を除去 */
  width: 120px; /* ボタンの幅を統一 */
  text-align: center; /* テキストを中央寄せ */
}

/* キャンセルボタン */
.modal-content .btn-secondary {
  background-color: #6c757d; /* 灰色 */
  color: #ffffff; /* 白文字 */
  border: none; /* 枠線を除去 */
  cursor: pointer; /* ポインターを表示 */
}

.modal-content .btn-secondary:hover {
  background-color: #5a6268; /* 濃い灰色 */
}

/* 削除ボタン */
.modal-content .btn-danger {
  background-color: #e62c3c; /* 赤色 */
  color: #ffffff; /* 白文字 */
  border: none; /* 枠線を除去 */
  cursor: pointer; /* ポインターを表示 */
}

.modal-content .btn-danger:hover {
  background-color: #c82333; /* 濃い赤色 */
}

/* アニメーション */
@keyframes fadeIn {
  from {
    opacity: 0; /* 不透明度 0 */
  }
  to {
    opacity: 1; /* 不透明度 1 */
  }
}
```

##### **7. テストコードの追加**
```ruby
RSpec.describe User, type: :model do
  before do
    @user = FactoryBot.create(:user) # 実際にデータベースに保存されるユーザー
  end

  describe 'ユーザーの削除' do
    context 'アカウント削除時' do
      it 'ユーザーがデータベースから削除されること' do
        expect { @user.destroy }.to change { User.count }.by(-1)
      end

      it '関連するrecordingsも削除されること' do
        FactoryBot.create(:recording, user: @user) # ユーザーに紐付いたRecording
        expect { @user.destroy }.to change { Recording.count }.by(-1)
      end
    end
  end
end

```

---

#### **完了条件**
- [x] ユーザーがアカウントを削除できる。
- [x] 関連する`recordings`データも削除される。
- [x] 削除後、トップページにリダイレクトされる。
- [x] 必要なRSpecテストが全て成功する。

---

#### **備考**
- 実装時には、JavaScriptを用いた削除確認モーダルを追加すると、より安全な操作が可能になります。
- 時間に余裕がある場合、データ削除前にバックアップやアカウント復元機能の実装を検討してください。
